// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: pointing.proto

package pointing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProcessingClient is the client API for Processing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessingClient interface {
	// Sends a greeting
	GetAntennaPointing(ctx context.Context, in *AntennaPointingRequest, opts ...grpc.CallOption) (*AntennaPointingReply, error)
}

type processingClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessingClient(cc grpc.ClientConnInterface) ProcessingClient {
	return &processingClient{cc}
}

func (c *processingClient) GetAntennaPointing(ctx context.Context, in *AntennaPointingRequest, opts ...grpc.CallOption) (*AntennaPointingReply, error) {
	out := new(AntennaPointingReply)
	err := c.cc.Invoke(ctx, "/pointing.Processing/GetAntennaPointing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessingServer is the server API for Processing service.
// All implementations must embed UnimplementedProcessingServer
// for forward compatibility
type ProcessingServer interface {
	// Sends a greeting
	GetAntennaPointing(context.Context, *AntennaPointingRequest) (*AntennaPointingReply, error)
	mustEmbedUnimplementedProcessingServer()
}

// UnimplementedProcessingServer must be embedded to have forward compatible implementations.
type UnimplementedProcessingServer struct {
}

func (UnimplementedProcessingServer) GetAntennaPointing(context.Context, *AntennaPointingRequest) (*AntennaPointingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAntennaPointing not implemented")
}
func (UnimplementedProcessingServer) mustEmbedUnimplementedProcessingServer() {}

// UnsafeProcessingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessingServer will
// result in compilation errors.
type UnsafeProcessingServer interface {
	mustEmbedUnimplementedProcessingServer()
}

func RegisterProcessingServer(s grpc.ServiceRegistrar, srv ProcessingServer) {
	s.RegisterService(&Processing_ServiceDesc, srv)
}

func _Processing_GetAntennaPointing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AntennaPointingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServer).GetAntennaPointing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pointing.Processing/GetAntennaPointing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServer).GetAntennaPointing(ctx, req.(*AntennaPointingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Processing_ServiceDesc is the grpc.ServiceDesc for Processing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Processing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pointing.Processing",
	HandlerType: (*ProcessingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAntennaPointing",
			Handler:    _Processing_GetAntennaPointing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pointing.proto",
}
